### ISSUE TITLE
Error when generating API

### ISSUE THREAD

**Issue by igorr0driguez** [26F-Studio/Emmy-love-api#12]
There are some errors occurring when trying to generate the API.

Here's the output

lua genEmmyAPI.lua
no field called table found at Source:getActiveEffects:returns[1]
no field called table found at Source:getEffect:parameters[2]
lua.exe: genEmmyAPI.lua:390: attempt to concatenate a nil value (field 'name')
stack traceback:
        genEmmyAPI.lua:390: in local 'f'
        genEmmyAPI.lua:41: in upvalue 'map_add'
        genEmmyAPI.lua:430: in local 'f'
        genEmmyAPI.lua:41: in upvalue 'map_add'
        genEmmyAPI.lua:449: in local 'gen_write_love'
        genEmmyAPI.lua:462: in main chunk
        [C]: in ?

On Windows 11 x64, using Lua 5.4.2.

**Comment by ImpleLee** [comment]
This is because Lua 5.4's `require` returns 2 values: the module and *loader data*, which is the path of the module by default, but other Lua versions (lua < 5.4) only returns the module. This difference makes the table returned by `love-api` completely different from previous ones, since it relies on `require` to import sublist.

**Comment by ImpleLee** [comment]
LOVE is bundled with luajit, so I think being compatible with luajit instead of lua5.4 is the better option. Although it is not totally impossible to support lua5.4 while not hurting the ability to be compatible with luajit, I don't generally think this would be a good idea.
